### ISSUE TITLE
python3.7

### ISSUE THREAD

**Issue by joggerjoel** [Carberra/twitch-bot-tutorial#7]
```
Traceback (most recent call last):
  File "twitch_tut.py", line 28, in <module>
    from lib import db, cmds, react, automod
  File "twitch-bot-tutorial/lib/db.py", line 29
    if (fetch := cur.fetchone()) is not None:
 
```

**Comment by parafoxia** [comment]
Either upgrade to 3.8 or greater, or rewrite it so it doesn't use the walrus operator. On a side note, please don't use the repo for support questions.
